### ISSUE TITLE
Blocking Error at Mod 5, Ex2, Task1, Step 11

### ISSUE THREAD

**Issue by Bethquinlan** [MicrosoftLearning/20535-ArchitectingMicrosoftAzureSolutions#11]
# Module: 05
#### Step: 11

Description of issue:  Deployment of Function App with Code using ARM fails.  Error message states "Not enough available instances to satisfy the request".  

![mod5-ex3-task1-step11-error](https://user-images.githubusercontent.com/17502756/35684061-a0c3e6fe-071a-11e8-8cce-5bc40046ba7a.png)

**Comment by edbakermct** [comment]
The lab instructions tell you to place this in the same resource group as the other 3 web apps.

The basic plan only supports 3 apps. So the new resource group would allow it to deploy into a separate App service plan

So in short it’s a typo you need to deploy the function in  MOD05FUNC rather than MOD05APPS

Yours

Ed

**Comment by seesharprun** [comment]
This bug has been fixed in a pull request #13 and I have released a new version of the lab instructions that fixes this issue.

https://github.com/MicrosoftLearning/20535-ArchitectingMicrosoftAzureSolutions/releases/tag/A-v1.0.1
