### ISSUE TITLE
Linux Web Apps wont deploy into same resource group as windows web apps

### ISSUE THREAD

**Issue by edbakermct** [MicrosoftLearning/20535-ArchitectingMicrosoftAzureSolutions#58]
# Module: 05
### Exercise 2 : Task: 1

Description of issue:

Linux Web Apps wont deploy into same resource group as windows web apps

Current work around - deploy second web app (Windows) into a new resource group

**Comment by tiagocostapt** [comment]
I just tested and it works fine in my subscription (Azure Pass).

<img width="922" alt="winlinux" src="https://user-images.githubusercontent.com/11490197/46968512-10dabd80-d0bc-11e8-9aa4-77810df52956.PNG">

Can you please test it again?

**Comment by edbakermct** [comment]
It works in different region as you have done not in same region it seems like it is new expected behaviour

Sent from iOS Outlook<https://aka.ms/qtex0l> protected by Microsoft Enterprise Mobility and Security
________________________________

**Comment by tiagocostapt** [comment]
humm let me check in the same region...

**Comment by tiagocostapt** [comment]
Yep. You're right. Under Limitations we ca read: 
"There is a current limitation in regards to not mixing Windows and Linux apps in the same resource group as well."

https://docs.microsoft.com/en-us/azure/app-service/containers/app-service-linux-intro#limitations

**Comment by edbakermct** [comment]
Yup new
Behaviour when Linux web apps went ga

Sent from iOS Outlook<https://aka.ms/qtex0l> protected by Microsoft Enterprise Mobility and Security
________________________________

**Comment by tiagocostapt** [comment]
@edbakermct, I did all the steps until the end of exercise 2 and never got the problem. Because this week I'm teaching this class a let my class of 17 to do the lab and have checked that 15 did the lab without any issue and 2 of then reported the same error has you did. I think this was due to Exercise 2 > Task 1 > Step 14. In this step you should use the name of the Node.js app that you had previous created in the "Web App Name" and not a new app name.

Can you please check this?
