### ISSUE TITLE
Broken Function Apps in Mod 10

### ISSUE THREAD

**Issue by seesharprun** [MicrosoftLearning/20535-ArchitectingMicrosoftAzureSolutions#63]
# Module: 10

The Function Apps are no longer working:

Related to https://github.com/azure-labs/cognitive-services-function/issues/1

**Comment by thommck** [comment]
I got this fixed by logging an issues on the referenced external git code. The owner explained the fault as:
The new version of Azure Functions requires you to use ILogger for logging instead of the old-school TraceWriter class.

Also, if you get Logic App compilation errors, check the code you pasted into the Logic App steps has standard straight apostrophes (') not fancy slanted ones
